"""empty message

Revision ID: 02df6a1d9724
Revises: 0134c2a86907
Create Date: 2022-11-28 13:49:27.904402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02df6a1d9724'
down_revision = '0134c2a86907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_characters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'people_id')
    )
    op.drop_table('favorites_people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['people.id'], name='favorites_people_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_people_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_people_pkey')
    )
    op.drop_table('fav_characters')
    # ### end Alembic commands ###
